services:
  traefik:
    networks:
      - proxy
      - sniply-observability
  db:
    ports: []

  api:
    ports: []
    labels:
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
  grafana:
    ports: []
    labels:
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=le
  prometheus:
    ports: []
  loki:
    ports: []
  tempo:
    ports: []
  otel-collector:
    ports: []